### ISSUE TITLE
Dependency injection prompted crash

### ISSUE THREAD

**Issue by cerver1** [sunderee/WiFi-Scanner#4]
--------- beginning of crash

2021-06-14 09:12:20.433 30669-30669/com.peteralexbizjak.wifiscanner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.peteralexbizjak.wifiscanner, PID: 30669
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.peteralexbizjak.wifiscanner/com.peteralexbizjak.wifiscanner.MainActivity}: org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
        at org.koin.core.context.GlobalContext.register(GlobalContext.kt:44)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.peteralexbizjak.wifiscanner.MainActivity.onCreate(MainActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by sunderee** [comment]
Hey, I'm sorry but I can't seem to replicate the issue. Can I politely ask you to elaborate more? At a bare minimum, I would like to ask you to provide

* Android SDK version
* which branch are you looking into (`master` or `rtt-ranging`), and
* what are the steps required to reach this particular error message?

**Comment by sunderee** [comment]
Since there was no response for 6 days I'm closing the issue. Will reopen if more info is provided. At the moment, on the master branch I cannot replicate the crash.
